version: '4'

services:
  # MySQL
  db:
    image: mariadb:10.2
    container_name: mysql_host
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbvolume:/var/lib/mysql:rw
      - ./app/database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./app/database/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: test_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=docker
      - PMA_PASSWORD=docker
    ports:
      - 8080:80
    networks:
      - network

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1323:1323
    depends_on:
      - db
    networks:
      - network

volumes:
  dbvolume:
    driver: local

networks:
  network:
    driver: bridge
